apiVersion: v1
kind: ConfigMap
metadata:
  name: service-template-web-configmap
  annotations:
    strategy.spinnaker.io/max-version-history: '3'
  labels:
    service: service-template
    app: web
  namespace: service-template
data:
  AWS_METADATA_SERVICE_TIMEOUT : "30"
  AWS_METADATA_SERVICE_NUM_ATTEMPTS: "3"
  CONTAINER_IMAGE: "{{ .Values.image.tag }}"
