{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "colors.serviceAccountName" . }}
  labels:
{{ include "colors.labels" . | indent 4 }}
{{- end -}}
