{{- if .Values.ingress.enabled -}}
{{- $fullName := include "apple-svc.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apple-svc.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.albManageTraffic.scheme }}
    {{ if .Values.ingress.albManageTraffic.prevService.name -}}
    alb.ingress.kubernetes.io/actions.forward-multiple-tg: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"{{ .Values.ingress.albManageTraffic.prevService.name }}","ServicePort":"{{ $svcPort }}","Weight":{{ .Values.ingress.albManageTraffic.prevService.weight}}},{"ServiceName":"{{ include "apple-svc.svcName" . }}","ServicePort":"{{ $svcPort }}","Weight":{{ .Values.ingress.albManageTraffic.currService.weight}}}],"TargetGroupStickinessConfig":{"Enabled":false,"DurationSeconds":200}}}
    {{- else -}}
    alb.ingress.kubernetes.io/actions.forward-multiple-tg: >
      {"Type":"forward","ForwardConfig":{"TargetGroups":[{"ServiceName":"{{ include "apple-svc.svcName" . }}","ServicePort":"{{ $svcPort }}","Weight":100}],"TargetGroupStickinessConfig":{"Enabled":false,"DurationSeconds":200}}}
    {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.ingress.albManageTraffic.path }}
            backend:
              serviceName: forward-multiple-tg
              servicePort: use-annotation
{{- end }}
